GROUND = " "
CONTROLLERS = ("right", "left", "up", "down")
AUXILIARIES = "space",
OPOSITES_DIRECTIONS = {"right": "left", "left": "right", "up": "down", "down": "up"}
VALID_INPUTS = CONTROLLERS + AUXILIARIES
HEIGHT = 30
WIDTH = 80
TOP_PADDING = 1
LEFT_PADDING = 1
MARGIN = 0
SCREEN_TOP = HEIGHT + TOP_PADDING + MARGIN + 2
SCREEN_WIDTH = WIDTH + LEFT_PADDING + MARGIN + 2
FIELD_TOP = MARGIN + TOP_PADDING + 1
FIELD_LEFT = MARGIN + LEFT_PADDING + 1
FIELD_RIGHT = MARGIN + LEFT_PADDING + WIDTH - 1
FIELD_BOTTOM = MARGIN + TOP_PADDING + HEIGHT - 1
STROKE_TOP = MARGIN + TOP_PADDING + .5
STROKE_LEFT = MARGIN + LEFT_PADDING - .5
STROKE_BOTTOM = 0
STROKE_RIGHT = 0

##
LEVEL_SNAKE_SPEED = {1: .2, 2: .1, 3: .05, 4: .04}
LEVEL_RABBIT_SPEED = {1: .7, 2: .5, 3: .3, 4: .1 }